# DB
DB_HOST = "127.0.0.1"
DB_PORT = 3306
DB_DBNAME = "nir_system"
DB_USER = "root"
DB_PASSWORD = "123456"


# SQLALCHEMY
SQLALCHEMY_POOL_SIZE = 5
SQLALCHEMY_POOL_TIMEOUT = 15
SQLALCHEMY_TRACK_MODIFICATIONS = False

# FLASK
FLASK_HOST = "127.0.0.1"
FLASK_PORT = 3003
RECV_FILE_DEST = "./7z"
UN7Z_FILE_DEST = "./data"
